require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Layout/LineLength:
  Exclude:
    - config/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*

Metrics/MethodLength:
  Exclude:
    - db/**/*
