require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*

Layout/LineLength:
  Exclude:
    - config/**/*
