---
development:
  cloud_name: <%= Rails.application.credentials.cloudinary.dig(:development, :cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.dig(:development, :api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.dig(:development, :api_secret) %>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <%= Rails.application.credentials.cloudinary.dig(:production, :cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.dig(:production, :api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.dig(:production, :api_secret) %>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <%= Rails.application.credentials.cloudinary.dig(:test, :cloud_name) %>
  api_key: <%= Rails.application.credentials.cloudinary.dig(:test, :api_key) %>
  api_secret: <%= Rails.application.credentials.cloudinary.dig(:test, :api_secret) %>
  enhance_image_tag: true
  static_file_support: false
